spring.application.name=Spring-data-exercises
spring.datasource.url=jdbc:postgresql://localhost:5432/spring-data-exercises
spring.datasource.username=coderkr
spring.datasource.password=1111
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

